name: Release

on:
  push:
    tags:
      - 'v*.*.*'

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@4305c38b25d97ef35a8ad1f985ccf2d2242004f2
      - run: cargo test --all

  build:
    needs: test
    uses: ./.github/workflows/build.yml
    with:
      release: true
      tag: ${{ github.ref_name }}

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download binary-x86_64-unknown-linux-musl
        uses: actions/download-artifact@v4
        with:
          name: binary-x86_64-unknown-linux-musl
          path: dist

      - name: Download binary-aarch64-unknown-linux-gnu
        uses: actions/download-artifact@v4
        with:
          name: binary-aarch64-unknown-linux-gnu
          path: dist

      - name: Download binary-aarch64-apple-darwin
        uses: actions/download-artifact@v4
        with:
          name: binary-aarch64-apple-darwin
          path: dist

      - name: Create GitHub Release
        uses: softprops/action-gh-release@da05d552573ad5aba039eaac05058a918a7bf631
        with:
          files: dist/*.tar.gz
          tag_name: ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
