name: Run Tests

on:
  push:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@4305c38
      - run: cargo test --all

  build:
    needs: test
    uses: ./.github/workflows/build.yml
    with:
      release: false
